"use strict";var sjcl={cipher:{},hash:{},keyexchange:{},mode:{},misc:{},codec:{},exception:{corrupt:function(a){this.toString=function(){return"CORRUPT: "+this.message};this.message=a},invalid:function(a){this.toString=function(){return"INVALID: "+this.message};this.message=a},bug:function(a){this.toString=function(){return"BUG: "+this.message};this.message=a},notReady:function(a){this.toString=function(){return"NOT READY: "+this.message};this.message=a}}};
"undefined"!=typeof module&&module.exports&&(module.exports=sjcl);
sjcl.cipher.aes=function(a){this.e[0][0][0]||this.i();var b,c,e,d,f=this.e[0][4],h=this.e[1];b=a.length;var g=1;if(4!==b&&6!==b&&8!==b)throw new sjcl.exception.invalid("invalid aes key size");this.d=[e=a.slice(0),d=[]];for(a=b;a<4*b+28;a++){c=e[a-1];if(0===a%b||8===b&&4===a%b)c=f[c>>>24]<<24^f[c>>16&255]<<16^f[c>>8&255]<<8^f[c&255],0===a%b&&(c=c<<8^c>>>24^g<<24,g=g<<1^283*(g>>7));e[a]=e[a-b]^c}for(b=0;a;b++,a--)c=e[b&3?a:a-4],d[b]=4>=a||4>b?c:h[0][f[c>>>24]]^h[1][f[c>>16&255]]^h[2][f[c>>8&255]]^h[3][f[c&
255]]};
sjcl.cipher.aes.prototype={encrypt:function(a){return v(this,a,0)},decrypt:function(a){return v(this,a,1)},e:[[[],[],[],[],[]],[[],[],[],[],[]]],i:function(){var a=this.e[0],b=this.e[1],c=a[4],e=b[4],d,f,h,g=[],k=[],n,m,l,p;for(d=0;0x100>d;d++)k[(g[d]=d<<1^283*(d>>7))^d]=d;for(f=h=0;!c[f];f^=n||1,h=k[h]||1){l=h^h<<1^h<<2^h<<3^h<<4;l=l>>8^l&255^99;c[f]=l;e[l]=f;m=g[d=g[n=g[f]]];p=0x1010101*m^0x10001*d^0x101*n^0x1010100*f;m=0x101*g[l]^0x1010100*l;for(d=0;4>d;d++)a[d][f]=m=m<<24^m>>>8,b[d][l]=p=p<<24^p>>>8}for(d=
0;5>d;d++)a[d]=a[d].slice(0),b[d]=b[d].slice(0)}};
function v(a,b,c){if(4!==b.length)throw new sjcl.exception.invalid("invalid aes block size");var e=a.d[c],d=b[0]^e[0],f=b[c?3:1]^e[1],h=b[2]^e[2];b=b[c?1:3]^e[3];var g,k,n,m=e.length/4-2,l,p=4,q=[0,0,0,0];g=a.e[c];a=g[0];var r=g[1],s=g[2],t=g[3],u=g[4];for(l=0;l<m;l++)g=a[d>>>24]^r[f>>16&255]^s[h>>8&255]^t[b&255]^e[p],k=a[f>>>24]^r[h>>16&255]^s[b>>8&255]^t[d&255]^e[p+1],n=a[h>>>24]^r[b>>16&255]^s[d>>8&255]^t[f&255]^e[p+2],b=a[b>>>24]^r[d>>16&255]^s[f>>8&255]^t[h&255]^e[p+3],p+=4,d=g,f=k,h=n;for(l=
0;4>l;l++)q[c?3&-l:l]=u[d>>>24]<<24^u[f>>16&255]<<16^u[h>>8&255]<<8^u[b&255]^e[p++],g=d,d=f,f=h,h=b,b=g;return q}
sjcl.bitArray={bitSlice:function(a,b,c){a=sjcl.bitArray.m(a.slice(b/32),32-(b&31)).slice(1);return void 0===c?a:sjcl.bitArray.clamp(a,c-b)},extract:function(a,b,c){var e=Math.floor(-b-c&31);return((b+c-1^b)&-32?a[b/32|0]<<32-e^a[b/32+1|0]>>>e:a[b/32|0]>>>e)&(1<<c)-1},concat:function(a,b){if(0===a.length||0===b.length)return a.concat(b);var c=a[a.length-1],e=sjcl.bitArray.getPartial(c);return 32===e?a.concat(b):sjcl.bitArray.m(b,e,c|0,a.slice(0,a.length-1))},bitLength:function(a){var b=a.length;return 0===
b?0:32*(b-1)+sjcl.bitArray.getPartial(a[b-1])},clamp:function(a,b){if(32*a.length<b)return a;a=a.slice(0,Math.ceil(b/32));var c=a.length;b&=31;0<c&&b&&(a[c-1]=sjcl.bitArray.partial(b,a[c-1]&2147483648>>b-1,1));return a},partial:function(a,b,c){return 32===a?b:(c?b|0:b<<32-a)+0x10000000000*a},getPartial:function(a){return Math.round(a/0x10000000000)||32},equal:function(a,b){if(sjcl.bitArray.bitLength(a)!==sjcl.bitArray.bitLength(b))return!1;var c=0,e;for(e=0;e<a.length;e++)c|=a[e]^b[e];return 0===
c},m:function(a,b,c,e){var d;d=0;for(void 0===e&&(e=[]);32<=b;b-=32)e.push(c),c=0;if(0===b)return e.concat(a);for(d=0;d<a.length;d++)e.push(c|a[d]>>>b),c=a[d]<<32-b;d=a.length?a[a.length-1]:0;a=sjcl.bitArray.getPartial(d);e.push(sjcl.bitArray.partial(b+a&31,32<b+a?c:e.pop(),1));return e},j:function(a,b){return[a[0]^b[0],a[1]^b[1],a[2]^b[2],a[3]^b[3]]}};
sjcl.codec.utf8String={fromBits:function(a){var b="",c=sjcl.bitArray.bitLength(a),e,d;for(e=0;e<c/8;e++)0===(e&3)&&(d=a[e/4]),b+=String.fromCharCode(d>>>24),d<<=8;return decodeURIComponent(escape(b))},toBits:function(a){a=unescape(encodeURIComponent(a));var b=[],c,e=0;for(c=0;c<a.length;c++)e=e<<8|a.charCodeAt(c),3===(c&3)&&(b.push(e),e=0);c&3&&b.push(sjcl.bitArray.partial(8*(c&3),e));return b}};
sjcl.codec.base64={k:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",fromBits:function(a,b,c){var e="",d=0,f=sjcl.codec.base64.k,h=0,g=sjcl.bitArray.bitLength(a);c&&(f=f.substr(0,62)+"-_");for(c=0;6*e.length<g;)e+=f.charAt((h^a[c]>>>d)>>>26),6>d?(h=a[c]<<6-d,d+=26,c++):(h<<=6,d-=6);for(;e.length&3&&!b;)e+="=";return e},toBits:function(a,b){a=a.replace(/\s|=/g,"");var c=[],e,d=0,f=sjcl.codec.base64.k,h=0,g;b&&(f=f.substr(0,62)+"-_");for(e=0;e<a.length;e++){g=f.indexOf(a.charAt(e));
if(0>g)throw new sjcl.exception.invalid("this isn't base64!");26<d?(d-=26,c.push(h^g>>>d),h=g<<32-d):(d+=6,h^=g<<32-d)}d&56&&c.push(sjcl.bitArray.partial(d&56,h,1));return c}};sjcl.codec.base64url={fromBits:function(a){return sjcl.codec.base64.fromBits(a,1,1)},toBits:function(a){return sjcl.codec.base64.toBits(a,1)}};sjcl.hash.sha256=function(a){this.d[0]||this.i();a?(this.c=a.c.slice(0),this.b=a.b.slice(0),this.a=a.a):this.reset()};sjcl.hash.sha256.hash=function(a){return(new sjcl.hash.sha256).update(a).finalize()};
sjcl.hash.sha256.prototype={blockSize:512,reset:function(){this.c=this.h.slice(0);this.b=[];this.a=0;return this},update:function(a){"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this.b=sjcl.bitArray.concat(this.b,a);b=this.a;a=this.a=b+sjcl.bitArray.bitLength(a);for(b=512+b&-512;b<=a;b+=512)this.f(c.splice(0,16));return this},finalize:function(){var a,b=this.b,c=this.c,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);b.push(Math.floor(this.a/
4294967296));for(b.push(this.a|0);b.length;)this.f(b.splice(0,16));this.reset();return c},h:[],d:[],i:function(){function a(a){return 0x100000000*(a-Math.floor(a))|0}var b=0,c=2,e;a:for(;64>b;c++){for(e=2;e*e<=c;e++)if(0===c%e)continue a;8>b&&(this.h[b]=a(Math.pow(c,0.5)));this.d[b]=a(Math.pow(c,1/3));b++}},f:function(a){var b,c,e=a.slice(0),d=this.c,f=this.d,h=d[0],g=d[1],k=d[2],n=d[3],m=d[4],l=d[5],p=d[6],q=d[7];for(a=0;64>a;a++)16>a?b=e[a]:(b=e[a+1&15],c=e[a+14&15],b=e[a&15]=(b>>>7^b>>>18^b>>>3^
b<<25^b<<14)+(c>>>17^c>>>19^c>>>10^c<<15^c<<13)+e[a&15]+e[a+9&15]|0),b=b+q+(m>>>6^m>>>11^m>>>25^m<<26^m<<21^m<<7)+(p^m&(l^p))+f[a],q=p,p=l,l=m,m=n+b|0,n=k,k=g,g=h,h=b+(g&k^n&(g^k))+(g>>>2^g>>>13^g>>>22^g<<30^g<<19^g<<10)|0;d[0]=d[0]+h|0;d[1]=d[1]+g|0;d[2]=d[2]+k|0;d[3]=d[3]+n|0;d[4]=d[4]+m|0;d[5]=d[5]+l|0;d[6]=d[6]+p|0;d[7]=d[7]+q|0}};sjcl.hash.sha1=function(a){a?(this.c=a.c.slice(0),this.b=a.b.slice(0),this.a=a.a):this.reset()};sjcl.hash.sha1.hash=function(a){return(new sjcl.hash.sha1).update(a).finalize()};
sjcl.hash.sha1.prototype={blockSize:512,reset:function(){this.c=this.h.slice(0);this.b=[];this.a=0;return this},update:function(a){"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this.b=sjcl.bitArray.concat(this.b,a);b=this.a;a=this.a=b+sjcl.bitArray.bitLength(a);for(b=this.blockSize+b&-this.blockSize;b<=a;b+=this.blockSize)this.f(c.splice(0,16));return this},finalize:function(){var a,b=this.b,c=this.c,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);
b.push(Math.floor(this.a/0x100000000));for(b.push(this.a|0);b.length;)this.f(b.splice(0,16));this.reset();return c},h:[1732584193,4023233417,2562383102,271733878,3285377520],d:[1518500249,1859775393,2400959708,3395469782],f:function(a){var b,c,e,d,f,h,g=a.slice(0),k=this.c;c=k[0];e=k[1];d=k[2];f=k[3];h=k[4];for(a=0;79>=a;a++)16<=a&&(g[a]=(g[a-3]^g[a-8]^g[a-14]^g[a-16])<<1|(g[a-3]^g[a-8]^g[a-14]^g[a-16])>>>31),b=19>=a?e&d|~e&f:39>=a?e^d^f:59>=a?e&d|e&f|d&f:79>=a?e^d^f:void 0,b=(c<<5|c>>>27)+b+h+g[a]+
this.d[Math.floor(a/20)]|0,h=f,f=d,d=e<<30|e>>>2,e=c,c=b;k[0]=k[0]+c|0;k[1]=k[1]+e|0;k[2]=k[2]+d|0;k[3]=k[3]+f|0;k[4]=k[4]+h|0}};
sjcl.mode.cbc={name:"cbc",encrypt:function(a,b,c,e){if(e&&e.length)throw new sjcl.exception.invalid("cbc can't authenticate data");e=sjcl.bitArray.j;var d,f,h=[];f=c;for(c=0;c+4<=b.length;c+=4)d=b.slice(c,c+4),d=a.encrypt(e(f,d)),h=h.concat(d),f=d;return h},decrypt:function(a,b,c,e){if(e&&e.length)throw new sjcl.exception.invalid("cbc can't authenticate data");if(128!==sjcl.bitArray.bitLength(c))throw new sjcl.exception.invalid("cbc iv must be 128 bits");if(sjcl.bitArray.bitLength(b)&127||!b.length)throw new sjcl.exception.corrupt("cbc ciphertext must be a positive multiple of the block size");
e=sjcl.bitArray.j;var d,f,h=[];f=c;for(c=0;c+4<=b.length;c+=4)d=b.slice(c,c+4),f=e(f,a.decrypt(d)),h=h.concat(f),f=d;return h}};sjcl.misc.hmac=function(a,b){this.l=b=b||sjcl.hash.sha256;var c=[[],[]],e,d=b.prototype.blockSize/32;this.g=[new b,new b];a.length>d&&(a=b.hash(a));for(e=0;e<d;e++)c[0][e]=a[e]^909522486,c[1][e]=a[e]^1549556828;this.g[0].update(c[0]);this.g[1].update(c[1])};
sjcl.misc.hmac.prototype.encrypt=sjcl.misc.hmac.prototype.mac=function(a){a=(new this.l(this.g[0])).update(a).finalize();return(new this.l(this.g[1])).update(a).finalize()};
sjcl.misc.pbkdf2=function(a,b,c,e,d){c=c||1E3;if(0>e||0>c)throw sjcl.exception.invalid("invalid params to pbkdf2");"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));d=d||sjcl.misc.hmac;a=new d(a);var f,h,g,k,n=[],m=sjcl.bitArray;for(k=1;32*n.length<(e||1);k++){d=f=a.encrypt(m.concat(b,[k]));for(h=1;h<c;h++){f=a.encrypt(f);for(g=0;g<f.length;g++)d[g]^=f[g]}n=n.concat(d)}e&&(n=m.clamp(n,e));return n};
sjcl.mode.cfb={name:"cfb",encrypt:function(a,b,c,e){return decrypt(a,b,c,e)},decrypt:function(a,b,c,e){if(128!==sjcl.bitArray.bitLength(c))throw new sjcl.exception.invalid("cfb iv must be 128 bits");if(e&&e.length)throw new sjcl.exception.invalid("cfb can't authenticate data");e=sjcl.bitArray.j;var d,f,h=[];f=c;for(c=0;c+4<=b.length;c+=4)d=b.slice(c,c+4),h=h.concat(e(a.encrypt(f),b.slice(c,c+4))),f=d;return h}};
